### ISSUE TITLE
Calling unindexed objects?

### ISSUE THREAD

**Issue by ghost** [hpnok/gg_rmg#1]
Attempted to run this on my server tonight. Came back after about 5 hours of unattended running to this error:
> Traceback (most recent call last):
  File "mapgenerator.pyw", line 211, in crop
TypeError: unorderable types: int() < NoneType()

> During handling of the above exception, another exception occurred:

> Traceback
(most recent call last):
  File "mapgenerator.pyw", line 672, in <module>
  File "mapgenerator.pyw", line 293, in build_map
  File "mapgenerator.pyw", line 231, in crop
IndexError

I figure it's attempting to call images which aren't stored in rmg_resources, and is unable to crop them, seeing as they don't exist. Then again, that's really presumptuous. When I came back, despite the error seemingly coming from mapgenerator.pyw, the error header itself was for mapgenerator.exe, prompting me to check mapgenerator.log for the error above.

**Comment by hpnok** [comment]
Should be fixed. The pixels used as a cue in ll--sb-16 weren't on the same line. The index error was just me being lazy. I added a proper description to the error and it should also returns the seed if it happens again.
